const degenPhrases = {
	poap: [
		'Did you say POAP? How dare you...',
		'let me get you your poap, oh dear looks like I misplaced them somehow... DEGEN can help with that ',
		'So you want a POAP? *sigh* DEGEN can help with that',
		'So you want a POAP? Love that for you.',
		'Did you say POAP? I want one! Where are they?',
		'I can\'t get you POAPs, but DEGEN can!',
		'POAPS? Ha that\'s almost as funny as "The Rug"',
		'There\'s no POAPs here ser, this is a Wendy\'s',
		'It\'s always "wenPOAP" this, "wenPOAP" that, never "Hi how are you doing today?"',
		'POAP??... Mods please send the ban hammer this way',
		'Did you say POAP?... nmgi',
		'POAPs are nice, what about a POAP pixel party 🎨',
	],
	app: [
		'DEV GUILD STRONK 💪',
		'Let me tell you about TOKEMAK...',
		'gm',
		'Hello ser, would you like to hear about our lord and savior Vitalik...',
		'Did you hear about Solana? lol',
		'Solana backwards is ****** OS',
		'I am not available at the moment... Please leave a message at the sound of the beep ... BEEP.',
		'Did you see the gas fees today? You don\'t want to know...',
		'Hello 👋',
		'Howdy!',
		'Hey!',
		'Go Bankless!',
		'Nice to meet you!',
		'It\'s great to see you!',
		'Ahoy!',
		'BANKLESSDAO STRONK 💪',
		'ALL GUILDS STRONK 💪',
		'wgmi',
		'The future is DAO.',
		'What\'s all this noise about the Constitution, is Nicolas Cage at it again 😂',
		'TO THE MOOOOOON!',
		'I am a complete degenerate.',
		'👀',
		'Hello! I\'m so glad you are here! wgmi fren',
	],
};

export default degenPhrases;