const degenPhrases = {
	down: [
		'only up here!',
		'things might be tough.. but I promise things will get better',
		'crypto is the future',
		'we are here fam',
	],
	poap: [
		'<@937748367235235861> can help with POAPs',
		'I can\'t get you POAPs, but <@937748367235235861> can!',
		'The more discord events you attend, the higher the chance of a POAP!',
	],
	app: [
		'DEV GUILD STRONK 💪',
		'Let me tell you about TOKEMAK...',
		'gm',
		'Hello ser, would you like to hear about our lord and savior Vitalik...',
		'The story of Ethereum goes like this... Once upon a time there was a little known player playing World of Warcraft...',
		'Hello fren! Make sure you never share your seed phrase :)',
		'I am not available at the moment... Please leave a message at the sound of the beep ... BEEP.',
		'Did you see the gas fees today? You don\'t want to know...',
		'Hello 👋',
		'Howdy!',
		'Hey!',
		'Go Bankless!',
		'Nice to meet you!',
		'It\'s great to see you!',
		'Ahoy!',
		'BANKLESSDAO STRONK 💪',
		'ALL GUILDS STRONK 💪',
		'wgmi',
		'The future is DAO.',
		'What\'s all this noise about the Constitution, is Nicolas Cage at it again 😂',
		'TO THE MOOOOOON!',
		'I am a complete degenerate.',
		'👀',
		'Hello! I\'m so glad you are here! wgmi fren',
		'Shill me your project 👂',
	],
};

export default degenPhrases;
